name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [macos-latest, windows-latest, ubuntu-latest]

    services:
      postgres:
        image: yassun4dev/plpgsql-check:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - run: |-
          sudo apt-get update
          sudo apt-get install --yes build-essential git python3 libpq-dev postgresql-client
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: "npm"
      - run: npm install
      - run: npm run build
      - run: ./sample/prepare.sh
      - run: npm run test:ci

      # - name: Build VSIX Package
      #   run: |
      #     VERSION=$(node -p "require('./package.json').version")
      #     npx vsce package -o vscode-plpgsql-lsp-${{ matrix.os }}-${VERSION}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}.vsix

      # - name: Upload Built VSIX
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: vscode-plpgsql-lsp
      #     path: vscode-plpgsql-lsp*.vsix
